Avoid creating Nostr auth events with same Id
Because it leads to authentication error, see [1].
The error is like this:
```
error: Request GET /api/v1/vm/1790  failed with code Unauthorized.
    Response: Auth check failed: Credential has already been used
```

[1] https://github.com/LNVPS/api/blob/master/API_DOCUMENTATION.md#nip-98-requirements